input_dir:
  dirpath: input

# only test a few, you can add more if you like
model:
  diffsbdd:
    name: DiffSBDD
    dir: /opt/veincent/GenAI_manuscript/ScrambleBench/models/DiffSBDD
    conda_env: benchmark_diffsbdd
  pocket2mol:
    name: Pocket2Mol
    dir: /opt/veincent/GenAI_manuscript/ScrambleBench/models/Pocket2Mol
    conda_env: benchmark_pocket2mol

generation:
  input: output
  output: AI_Generation
  parameter:
    box_size: 16
    num_sample: 50,100
    name: 5ht2c_prepared_0

post_generation:
  input: AI_Generation
  output: cheminformatics_input_prepared
  pick_last: Pocket2Mol

analysis:
  genbench3d:
    input: cheminformatics_input_prepared
    output: cheminformatics_analysis
    genbench3d_dir: /mnt/sod/Veincent/manuscript/ScrambleBench/models/genbench3d
    conda_env: benchmark_genbench3d
    schrodinger_dir: /opt/schrodinger2025-4
    genbench3d_config: /mnt/sod/Veincent/manuscript/ScrambleBench/models/genbench3d/GenAI_evaluation.yaml
    do_complex_forcefield_minimisation: True
    do_docking_forcefield_minimisation: True
    skip_genbench3d_protonation: True

  redocking:
    protonation: 
      method: molgpka
      input: cheminformatics_input_prepared
      output: docking
      env: benchmark_easydock

    docking:
      easydock:
        input: docking
        output: vina_output
        conda_env: benchmark_easydock
        protein_pdbqt_preparation: adfr
        protein_pdbqt_executable: /opt/veincent/software/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/bin/prepare_receptor 
        protein_preparation: pdbfixer
        docking_program: vina
        protonation: null
        config_fname: config/easydock_config_5HT2C.yml

      glide:
        input: cheminformatics_input_prepared
        output: glide_output
        schrodinger_dir: /opt/schrodinger2025-4
        reward_intra_hbonds: null
        protonation: ligprep
        protein_preparation: protwizard

  diversity:
    input: cheminformatics_input_prepared
    output: diversity
    conda_env: python_tsp
    method:
    - distance: ecfp
      diversity: hamdiv
    - distance: mces
      diversity: hamdiv
    - distance: null
      diversity: generic_bm

  virtual_hit:
    input: glide_output
    output: virtual_hit
    query: 'QED >= 0.5 and glide_redocking_score <= -8 AND MW >= 300 and MW <= 500'
    filter: PAINS
    
report:
  rmsd: True
  docking_score: True
  virtual_hit: True
  plot: violin
  qed: True




