INPUT_KEY = 'input'
INPUT_DIR_KEY = 'input_dir'
MODEL_KEY = 'model'
GENERATION_KEY = 'generation'
GENERATION_PARAMETER_KEY = 'parameter'
POST_GENERATION_KEY = 'post_generation'
GENBENCH3D_KEY = 'genbench3d'